models/Predio.py
from utils.db import db


class Predio(db.Model):
    idPredio = db.Column(db.Integer, primary_key=True)
    nombrePropietario = db.Column(db.String(100))
    direccionPredio = db.Column(db.String(100))
    areaPredio = db.Column(db.Float)
    tipoSuelo = db.Column(db.String(100))
    valorPredio = db.Column(db.Float)
    distrito = db.Column(db.String(100))

    def __init__(self, nombrePropietario, direccionPredio, areaPredio, tipoSuelo, valorPredio, distrito):       
        self.nombrePropietario = nombrePropietario
        self.direccionPredio = direccionPredio
        self.areaPredio = areaPredio
        self.tipoSuelo = tipoSuelo
        self.valorPredio = valorPredio
        self.distrito = distrito
        

app.py
from flask import Flask
from routes.Predio import predios
from flask_sqlalchemy import SQLAlchemy
from config import DATABASE_CONNECTION_URI

app = Flask(__name__)

# settings
app.secret_key = 'zawarudo777'
print(DATABASE_CONNECTION_URI)
app.config["SQLALCHEMY_DATABASE_URI"] = DATABASE_CONNECTION_URI
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

# no cache
app.config['SEND_FILE_MAX_AGE_DEFAULT'] = 0

SQLAlchemy(app)

app.register_blueprint(predios)

routes/Predio.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.Predio import Predio
from utils.db import db

predios = Blueprint("predios", __name__)


@predios.route('/')
def index():
    predios = Predio.query.all()
    return render_template('index.html', predios = predios)


@predios.route('/new', methods=['POST'])
def add_predio():
    if request.method == 'POST':

        # receive data from the form
    
        nombrePropietario = request.form['nombrePropietario']
        direccionPredio = request.form['direccionPredio']
        areaPredio = request.form['areaPredio']
        tipoSuelo = request.form['tipoSuelo']
        valorPredio = request.form['valorPredio']
        distrito = request.form['distrito']

        # create a new Predio object
        new_predio = Predio(nombrePropietario, direccionPredio, areaPredio, tipoSuelo, valorPredio, distrito)

        # save the object into the database
        db.session.add(new_predio)
        db.session.commit()

        flash('Predio added successfully!')

        return redirect(url_for('predios.index'))


@predios.route("/update/<string:idPredio>", methods=["GET", "POST"])
def update(idPredio):
    # get predio by Id
    print(idPredio)
    predio = Predio.query.get(idPredio)

    if request.method == "POST":
        predio.nombrePropietario = request.form['nombrePropietario']
        predio.direccionPredio = request.form['direccionPredio']
        predio.areaPredio = request.form['areaPredio']
        predio.tipoSuelo = request.form['tipoSuelo']
        predio.valorPredio = request.form['valorPredio']
        predio.distrito = request.form['distrito']

        db.session.commit()

        flash('Predio updated successfully!')

        return redirect(url_for('predios.index'))

    return render_template("update.html", predio=predio)


@predios.route("/delete/<idPredio>", methods=["GET"])
def delete(idPredio):
    predio = Predio.query.get(idPredio)
    db.session.delete(predio)
    db.session.commit()

    flash('Predio deleted successfully!')

    return redirect(url_for('predios.index'))


@predios.route("/about")
def about():
    return render_template("about.html")

templates/about.html
{% extends 'layout.html' %}

{% block body %}

<div class="row text-brown">
  <h1>About</h1>
  <p> Grupo 7 "The Seven" Integrantes: Barbieri Canales Marcelo Alessandro, Valer Perez Fabrizio Alexis</p>
</div>

{% endblock %}

templates/index.html
{% extends 'layout.html' %}

{% block title %}
  INVENTARIAR PREDIOS - G7 | Home 
{% endblock %}

{% block body %}

 <!-- FORM -->

    <!-- MESSAGE -->
    {% include 'partials/_message.html' %}

    <!-- FORM -->
    {%  include 'partials/_taskForm.html' %}
  

 <!-- predios list -->

  <div class="col-md-7 container py-5">
    {% for predio in predios %}
      <div class="card mb-1 bg-black text-white">
        <div class="card-body py-2 px-3">
          <div class="d-flex justify-content-between">
            <h5 class="card-title h6">{{ predio.nombrePropietario}}</h5>
            <div>
              <a href="{{ url_for('predios.update', idPredio=predio.idPredio) }}" class="btn btn-primary btn-sm rounded-0">Editar</a>
              <a href="{{ url_for('predios.delete', idPredio=predio.idPredio) }}" class="btn btn-danger btn-sm rounded-0">Eliminar</a>
            </div>
          </div>
          <p class="card-text">{{ predio.direccionPredio }}</p>
          <p class="card-text">{{ predio.areaPredio }}</p>
          <p class="card-text">{{ predio.tipoSuelo }}</p>
          <p class="card-text">{{ predio.valorPredio }}</p>
          <p class="card-text">{{ predio.distrito }}</p>
        </div>
      </div>
    {% endfor %}
  </div>


{% endblock %} 

templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock %}</title>
    <!-- <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/bootstrap.min.css')}}"
    /> -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/main.css')}}"
    />
  </head>
  <body>
    {% include 'partials/_navbar.html' %}

    <div class="container p-2">{% block body %} {% endblock %}</div>

    <!-- scripts -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/partials/_message.html
{% with messages = get_flashed_messages() %} {% if messages %} {% for message in
messages %}
<div class="alert alert-info alert-dismissible fade show" role="alert">
  {{message}}
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  ></button>
</div>
{% endfor %} {% endif %} {% endwith %}

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-black">
  <div class="container">
    <a class="navbar-brand" href="/">INVENTARIAR PREDIOS - G7</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/about">About</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/partials/_taskForm.html
<form action="/new" method="POST" class="card bg-black text-light" class="row justify-content-center">
  <div class="row justify-content-center container py-5">
    <h1 class="h20 mb-7 col-md-15">Agregar Predio</h1>

    <div class="container py-5 form-group col-md-5">
      <label for="nombrePropietario">Escriba el nombre del propietario del predio:</label>
      <input
        type="text"
        name="nombrePropietario"
        class="form-control rounded-0 bg-white border-0 text-black"
        placeholder="Escribir nombrePropietario"
        autofocus
      />
    </div>

    <div class="container py-5 form-group col-md-5 ">
      <label for="direccionPredio">Escriba la dirección del predio:</label>
      <input
        type="text"
        name="direccionPredio"
        class="form-control rounded-0 bg-white border-0 text-black"
        placeholder="Escribir direccionPredio"
        required
      />
    </div>
    <div class="container py-7 form-group col-md-5">
      <label for="areaPredio">Indique el area del predio en metros cuadrados:</label>
      <input
        type="text"
        name="areaPredio"
        class="form-control rounded-0 bg-white border-0 text-black"
        placeholder="Escribir areaPredio"
        required
      />
    </div>
    <div class="container py-7 form-group col-md-5">
      <label for="tipoSuelo">Indique el tipo de suelo que presenta el predio:</label>
      <input
        type="text"
        name="tipoSuelo"
        class="form-control rounded-0 bg-white border-0 text-black"
        placeholder="Escribir tipoSuelo"
        required
      />
    </div>
    <div class="container py-5 form-group col-md-5">
      <label for="valorPredio">Indique el valor del predio:</label>
      <input
        type="text"
        name="valorPredio"
        class="form-control rounded-0 bg-white border-0 text-black"
        placeholder="Escribir valorPredio"
        required
      />
    </div>
    <div class="container py-5 form-group col-md-5">
      <label for="distrito">Escriba el distrito en el que se ubica el predio:</label>
      <input
        type="text"
        name="distrito"
        class="form-control rounded-0 bg-white border-0 text-black"
        placeholder="Escribir distrito"
        required
      />
    </div>

    <div class="container py-7 form-group col-md-11">
      <button class="btn btn-primary btn-lg">Registrar</button>
    </div>
  </div>
</form>

templates/update.html
{% extends "layout.html" %} {% block body %}

<div class="col-md-4 offset-md-4">
  <div class="card card-body bg-dark text-white">
    <h1>Edit Task</h1>

    <form action="{{url_for('predios.update', idPredio=predio.idPredio)}}" method="POST">
      <div class="mb-3">
        <label for="nombrePropietario">Escriba el nombre del propietario del predio:</label>
        <input
          type="text"
          name="nombrePropietario"
          value="{{predio.nombrePropietario}}"
          class="form-control bg-dark text-white rounded-0"
        />
      </div>
      <div class="mb-3">
        <label for="direccionPredio">Escriba la dirección del predio:</label>
        <input
          type="text"
          name="direccionPredio"
          value="{{predio.direccionPredio}}"
          class="form-control bg-dark text-white rounded-0"
        />
      </div>
      <div class="mb-3">
        <label for="areaPredio">Indique la magnitud del area del predio en metros cuadrados:</label>
        <input
          type="text"
          name="areaPredio"
          value="{{predio.areaPredio}}"
          class="form-control bg-dark text-white rounded-0"
        />
      </div>
      <div class="mb-3">
        <label for="tipoSuelo">Indique el tipo de suelo que presenta el predio:</label>
        <input
          type="text"
          name="tipoSuelo"
          value="{{predio.tipoSuelo}}"
          class="form-control bg-dark text-white rounded-0"
        />
      </div>
      <div class="mb-3">
        <label for="valorPredio">Indique el valor del predio:</label>
        <input
          type="text"
          name="valorPredio"
          value="{{predio.valorPredio}}"
          class="form-control bg-dark text-white rounded-0"
        />
      </div>
      <div class="mb-3">
        <label for="distrito">Escriba el distrito en el que se ubica el predio:</label>
        <input
          type="text"
          name="distrito"
          value="{{predio.distrito}}"
          class="form-control bg-dark text-white rounded-0"
        />
      </div>

      <button class="btn btn-primary">Actualizar</button>
    </form>
  </div>
</div>

{% endblock %}